services:
  otenkisan_backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: otenkisan_backend
    container_name: otenkisan_backend
    volumes:
      - type: bind
        source: "./backend"
        target: "/var/otenkisan/backend"
      - type: bind
        source: "./public"
        target: "/var/otenkisan/public"
    restart: always
    tty: true
  otenkisan_frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: otenkisan_frontend
    container_name: otenkisan_frontend
    ports:
      - "8003:80"
    volumes:
      - type: bind
        source: "./public"
        target: "/var/otenkisan/public"
    restart: always
