version: "3"
services:
  otenkisan_backend:
    build:
      context: .
      dockerfile: ./Dockerfile_backend
    image: otenkisan_backend
    container_name: otenkisan_backend
    volumes:
      - type: bind
        source: "./"
        target: "/var/otenkisan/"
    restart: always
    tty: true
  otenkisan_frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    image: otenkisan_frontend
    container_name: otenkisan_frontend
    ports:
      - "8003:80"
    volumes:
      - type: bind
        source: "./"
        target: "/var/otenkisan/"
      - type: bind
        source: "./conf.d/nginx.conf"
        target: "/etc/nginx/conf.d/nginx.conf"
    restart: always
